serviceAccount:
  create: true
  name: fluent-bit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::136600023723:role/EKSFluentBitRole

cloudWatch:
  enabled: true
  logGroupName: /aws/eks/fluentbit/logs
  logStreamPrefix: from-fluent-bit-
  region: us-east-1

firehose:
  enabled: false

kinesis:
  enabled: false

elasticsearch:
  enabled: false
