name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-eks-python-app:latest .

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-eks-python-app:latest

    # - name: Install kubectl
    #   run: |
    #     curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.29.0/2024-04-16/bin/linux/amd64/kubectl
    #     chmod +x ./kubectl
    #     sudo mv ./kubectl /usr/local/bin/

    # - name: Install Helm
    #   run: |
    #     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    # - name: Update kubeconfig
    #   run: |
    #     aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name my-eks-cluster

    # - name: Deploy with Helm
    #   run: |
    #     helm upgrade --install myapp ./helm \
    #       --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-eks-python-app \
    #       --set image.tag=latest
